version: "3"

services:
  project_db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - '/var/postgresql/data:/var/postgresql/data'
  project_app:
    build: .
    env_file: .env
    depends_on:
      - 'project_db'
    ports:
      - '8080:8080'
